[tools]
golangci-lint = "2.13.1" # go より先に配置しないと go/bin/ のバイナリが優先されてしまう
go = "1.27.0"
goreleaser = "2.18.0"

[tasks.build]
run = "go build ./..."

[tasks.test]
run = "go test ./..."

[tasks.lint]
run = "golangci-lint run --fix"

[tasks.release-check]
run = "goreleaser check"
